spring.application.name=campusconnect

# ===============================
# MySQL Database
# ===============================

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/collect_connect}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:campusconnect}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


# ===============================
# Server
# ===============================

server.port=${PORT:8080}


# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET:CampusConnectSecretKey2026ForJwtAuthenticationVerySecureKey}
jwt.expiration=${JWT_EXPIRATION:86400000}


# ===============================
# Frontend / CORS
# ===============================

frontend.url=${FRONTEND_URL:http://localhost:5173}


# ===============================
# Logging
# ===============================

logging.level.org.springframework.security=INFO
logging.level.com.campusconnect.demo.config=INFO